# Generated by Django 5.2.11 on 2026-02-27 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('billboard_type', models.CharField(choices=[('LED', 'LED Billboard'), ('TRADITIONAL', 'Traditional Billboard'), ('DIGITAL', 'Digital Billboard'), ('VINYL', 'Vinyl Billboard'), ('NEON', 'Neon Billboard'), ('OTHER', 'Other')], default='TRADITIONAL', max_length=20)),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in feet', max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in feet', max_digits=6)),
                ('illumination', models.BooleanField(default=False, help_text='Does the billboard have lighting?')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('MAINTENANCE', 'Under Maintenance'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20)),
                ('is_verified', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Billboards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillboardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='billboards/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='billboards.billboard')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
