# Generated by Django 5.2.11 on 2026-02-27 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billboards', '0001_initial'),
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_price', models.DecimalField(decimal_places=2, help_text='Your price for this campaign', max_digits=10)),
                ('message', models.TextField(help_text='Message to the customer explaining your proposal')),
                ('proposed_start_date', models.DateField(help_text='Proposed campaign start date')),
                ('proposed_end_date', models.DateField(help_text='Proposed campaign end date')),
                ('includes_design', models.BooleanField(default=False, help_text='Include ad design service')),
                ('includes_installation', models.BooleanField(default=True, help_text='Include ad installation')),
                ('additional_notes', models.TextField(blank=True, help_text='Any additional terms or notes')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('billboard', models.ForeignKey(help_text='The billboard being offered for this proposal', on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='billboards.billboard')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='proposals.proposal')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('proposal', 'bidder')},
            },
        ),
        migrations.CreateModel(
            name='BidMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bidding.bid')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
