# Generated by Django 5.2.11 on 2026-02-27 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ad_type', models.CharField(choices=[('PRODUCT', 'Product Launch'), ('BRAND', 'Brand Awareness'), ('EVENT', 'Event Promotion'), ('SERVICE', 'Service Promotion'), ('SEASONAL', 'Seasonal Campaign'), ('OTHER', 'Other')], default='BRAND', max_length=20)),
                ('campaign_name', models.CharField(max_length=200)),
                ('ad_content', models.TextField(help_text='The actual ad content/message to display')),
                ('preferred_location', models.TextField(blank=True, help_text='Preferred city/area')),
                ('preferred_billboard_type', models.CharField(choices=[('ANY', 'Any Type'), ('LED', 'LED Billboard'), ('TRADITIONAL', 'Traditional Billboard'), ('DIGITAL', 'Digital Billboard')], default='ANY', max_length=20)),
                ('min_width', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum width in feet', max_digits=6, null=True)),
                ('min_height', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum height in feet', max_digits=6, null=True)),
                ('requires_illumination', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget_min', models.DecimalField(decimal_places=2, help_text='Minimum budget', max_digits=10)),
                ('budget_max', models.DecimalField(decimal_places=2, help_text='Maximum budget', max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open for Bids'), ('IN_REVIEW', 'In Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('IMAGE', 'Image'), ('DESIGN', 'Ad Design'), ('REFERENCE', 'Reference Material'), ('OTHER', 'Other')], default='REFERENCE', max_length=20)),
                ('file', models.FileField(upload_to='proposals/attachments/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='proposals.proposal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
